dist: trusty
language: bash
branches:
    only:
        - master
script:
      - echo "Logging in as ${DOCKER_USER}"
      - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - bash build.sh
      