apiVersion: v1
kind: Service
metadata:
  name: streammachine-web
spec:
  selector:
    name: streammachine
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: streammachine-media
spec:
  selector:
    name: streammachine
  ports:
  - protocol: TCP
    port: 1935
    targetPort: 1935
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: streammachine-media-api
spec:
  selector:
    name: streammachine
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer